name: build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      bochs_display_library: nogui
      bochs_command_mode: run
    steps:
      - uses: actions/checkout@v3
      - run: make prepare.install.case
      - run: make bochs.hello.case
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      bochs_display_library: nogui
      bochs_command_mode: run
    steps:
      - uses: actions/checkout@v3
      - run: make prepare.install.case
      - run: make bochs.hello.case
#  build-windows:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#      - run: make bochs.hello.case
